# Generated by Django 4.1 on 2022-08-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giphy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='link',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
