# Generated by Django 4.1 on 2022-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giphy', '0002_gif_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='link',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
